services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: tasks_rs_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres:


